name: test

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/smoke-testing.yml"
      - "3rdparty/include/**"
      - "include/**"
      - "source/**"
      - "sample/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "*.sln"
      - "assets/**"
      - "MaaDeps/**"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/smoke-testing.yml"
      - "3rdparty/include/**"
      - "include/**"
      - "source/**"
      - "sample/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "*.sln"
      - "assets/**"
      - "MaaDeps/**"
  workflow_dispatch:

jobs:
  smoke-testing-cmake:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bootstrap MaaDeps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 maadeps-download.py x64-windows

      - name: Build MAA
        run: |
          cmake --preset "MSVC 2022" -DMAADEPS_TRIPLET="maa-x64-windows"

          cmake --build build --preset "MSVC 2022 - Release" -j 16
          cmake --install build --prefix install

      - name: Run Testing
        run: |
          .\install\Release\sample.exe

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: .\install\Release\debug

  smoke-testing:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap MaaDeps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 maadeps-download.py x64-windows

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Build MaaSample
        run: |
          MSBUILD MAA.sln /t:rebuild /p:Configuration="Debug" /p:Platform="x64" /m

      - name: Run Testing
        run: |
          .\x64\Debug\Sample.exe

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: .\x64\Debug\debug
